replicaCount: 1

image:
  repository: axel7720/testapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
